name: Continuous integration

on:
  pull_request:
  push:

jobs:
  os_tests:
    name: "Tests / OS: ${{ matrix.os }} - ${{ matrix.channel }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        channel:
        - stable
        - beta
        - nightly
        - 1.23.0
        os:
        - macos-10.15
        - windows-2019
        - ubuntu-20.04
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update rust
      run: rustup update ${{ matrix.channel }} --no-self-update

    - name: Tests
      run: cargo +${{ matrix.channel }} test --all
